package main

import (
	"bufio"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// ============================================================================
// Module: Code Audit — Phase 52 (Generated by Gemini CLI, enhanced by PM)
// Counts Go files, lines, functions, test files in a directory.
// ============================================================================

// AuditResult holds code audit metrics
type AuditResult struct {
	GoFiles   int
	TestFiles int
	TotalLines int
	FuncCount  int
}

// RunCodeAudit scans rootDir and returns code metrics
func RunCodeAudit(rootDir string) AuditResult {
	var result AuditResult

	_ = filepath.WalkDir(rootDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(d.Name(), ".go") {
			return nil
		}

		result.GoFiles++
		if strings.HasSuffix(d.Name(), "_test.go") {
			result.TestFiles++
		}

		file, err := os.Open(path)
		if err != nil {
			return nil
		}
		defer file.Close()

		scanner := bufio.NewScanner(file)
		for scanner.Scan() {
			line := scanner.Text()
			result.TotalLines++
			trimmed := strings.TrimSpace(line)
			if strings.HasPrefix(trimmed, "func ") {
				result.FuncCount++
			}
		}

		return nil
	})

	fmt.Printf("[코드감사] %s\n", rootDir)
	fmt.Printf("  Go 파일: %d개\n", result.GoFiles)
	fmt.Printf("  테스트 파일: %d개\n", result.TestFiles)
	fmt.Printf("  총 라인: %d줄\n", result.TotalLines)
	fmt.Printf("  함수 수: %d개\n", result.FuncCount)

	return result
}
